### ISSUE TITLE
Allow to check for optional packages

### ISSUE THREAD

**Issue by mydea** [pzuraq/ember-compatibility-helpers#38]
In the process of https://github.com/ember-cli/ember-fetch/pull/392, I learned that this addon throws an error at build time if trying to check for an addon that is not installed.

It would be nice to have an option to check for an optional package version!

**Comment by rwjblue** [comment]
Ya, agreed! 

What do you think @pzuraq?

**Comment by pzuraq** [comment]
Yeah, I’m on board with that idea. Maybe a `has` method?

**Comment by mydea** [comment]
E.g. something like `has(packageName, { min, max })` or something like this? To allow to also check for certain (optional) versions?

**Comment by xg-wang** [comment]
Closed by https://github.com/pzuraq/ember-compatibility-helpers/pull/54? @pzuraq  @igorT

**Comment by igorT** [comment]
I believe so.

**Comment by mydea** [comment]
:+1:
